tap "osx-cross/arm"
tap "osx-cross/avr"
tap "qmk/qmk"
brew "pulumi"
brew "k9s"
brew "dry"
brew "avrdude"
brew "aws-iam-authenticator"
brew "awscli"
brew "bmon"
brew "btop"
brew "cmatrix"
brew "convco"
brew "coreutils"
brew "cosign"
brew "cowsay"
brew "diffutils"
brew "docker-clean"
brew "docutils", link: false
brew "eksctl"
brew "exif"
brew "findutils"
brew "fortune"
brew "fzf"
brew "gcc"
brew "libavif"
brew "gh"
brew "git"
brew "gnu-sed"
brew "go"
brew "helm"
brew "hugo"
brew "iperf"
brew "iproute2mac"
brew "jq"
brew "k6"
brew "kind"
brew "kn"
brew "kubernetes-cli"
brew "krew"
brew "kube-linter"
brew "kubeseal"
brew "lolcat"
brew "minicom"
brew "minikube"
brew "nmap"
brew "oras"
brew "pre-commit"
brew "ripgrep"
brew "stern"
brew "tldr"
brew "tmux"
brew "tree"
brew "uv"
brew "watch"
brew "wget"
brew "yamllint"
brew "qmk/qmk/qmk"
brew "ctlptl"
brew "tilt"
cask "1password-cli"
cask "db-browser-for-sqlite"
cask "discord"
cask "docker-desktop"
cask "drawio"
cask "firefox"
cask "gcloud-cli"
cask "google-chrome"
cask "iterm2"
cask "karabiner-elements"
cask "keka"
cask "mongodb-compass"
cask "notion"
cask "postman"
cask "pritunl"
cask "rectangle"
cask "slack"
cask "teamviewer"
cask "visual-studio-code"
cask "wireshark-app"
# vscode "alexkrechik.cucumberautocomplete"
# vscode "bradlc.vscode-tailwindcss"
# vscode "charliermarsh.ruff"
# vscode "coder.coder-remote"
# vscode "dbaeumer.vscode-eslint"
# vscode "docker.docker"
# vscode "donjayamanne.githistory"
# vscode "eamodio.gitlens"
# vscode "github.codespaces"
# vscode "golang.go"
# vscode "gruntfuggly.todo-tree"
# vscode "hashicorp.terraform"
# vscode "mhutchie.git-graph"
# vscode "mindaro-dev.file-downloader"
# vscode "ms-azuretools.vscode-containers"
# vscode "ms-azuretools.vscode-docker"
# vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
# vscode "ms-python.black-formatter"
# vscode "ms-python.debugpy"
# vscode "ms-python.isort"
# vscode "ms-python.mypy-type-checker"
# vscode "ms-python.python"
# vscode "ms-python.vscode-pylance"
# vscode "ms-python.vscode-python-envs"
# vscode "ms-toolsai.jupyter"
# vscode "ms-toolsai.jupyter-keymap"
# vscode "ms-toolsai.jupyter-renderers"
# vscode "ms-toolsai.vscode-jupyter-cell-tags"
# vscode "ms-toolsai.vscode-jupyter-slideshow"
# vscode "ms-vscode-remote.remote-containers"
# vscode "ms-vscode-remote.remote-ssh"
# vscode "ms-vscode-remote.remote-ssh-edit"
# vscode "ms-vscode.cmake-tools"
# vscode "ms-vscode.cpp-devtools"
# vscode "ms-vscode.cpptools"
# vscode "ms-vscode.cpptools-extension-pack"
# vscode "ms-vscode.cpptools-themes"
# vscode "ms-vscode.makefile-tools"
# vscode "ms-vscode.remote-explorer"
# vscode "ms-vscode.remote-server"
# vscode "ms-vscode.vscode-typescript-next"
# vscode "ms-vsliveshare.vsliveshare"
# vscode "pkief.material-icon-theme"
# vscode "redhat.vscode-commons"
# vscode "redhat.vscode-xml"
# vscode "redhat.vscode-yaml"
# vscode "shd101wyy.markdown-preview-enhanced"
# vscode "sonarsource.sonarlint-vscode"
# vscode "streetsidesoftware.code-spell-checker"
# vscode "tamasfe.even-better-toml"
# vscode "twxs.cmake"
# vscode "usernamehw.errorlens"
# vscode "vscodevim.vim"
# vscode "waderyan.gitblame"
# vscode "yzhang.markdown-all-in-one"
# vscode "zhuangtongfa.material-theme"
# go "github.com/klauspost/asmfmt/cmd/asmfmt"
# go "github.com/go-delve/delve/cmd/dlv"
# go "github.com/kisielk/errcheck"
# go "github.com/davidrjenni/reftools/cmd/fillstruct"
# go "github.com/rogpeppe/godef"
# go "golang.org/x/tools/cmd/goimports"
# go "github.com/golangci/golangci-lint/cmd/golangci-lint"
# go "golang.org/x/lint/golint"
# go "github.com/fatih/gomodifytags"
# go "golang.org/x/tools/gopls"
# go "golang.org/x/tools/cmd/gorename"
# go "github.com/jstemmer/gotags"
# go "golang.org/x/tools/cmd/guru"
# go "github.com/koron/iferr"
# go "github.com/josharian/impl"
# go "honnef.co/go/tools/cmd/keyify"
# go "github.com/fatih/motion"
# go "honnef.co/go/tools/cmd/staticcheck"
krew "konfig"
